## ------------------------------
#  GAME
## ------------------------------
type Game  {
  id: ID!
  cards: [Card!]!
  createdAt: String!
  updatedAt: String!
}

type Card {
  id: ID!
  name: String!
  isTurned: Boolean!
  isMatched: Boolean!
  position: Float!
  createdAt: String!
  updatedAt: String!
}



## ------------------------------
#  INPUTS / OUTPUTS
## ------------------------------


## ------------------------------
#  QUERIES
## ------------------------------
type Query  {
  game(id: ID!): Game!
}

## ------------------------------
#  MUTATIONS
## ------------------------------
type Mutation {
  newGame: Game!
  updateGame(
    gameId: ID!
    cardId: ID!
    isTurned: Boolean!
  ): Game!
  flipCard(
    gameId: ID!
    cardId: ID!
    isTurned: Boolean!
    isMatched: Boolean!
  ): Card!
}
